config/routes.rb
Proyecto::Application.routes.draw do

  resources :pianizm  do
    collection do
      get 'logout'
    end

  end

  resources :user do
    collection do
      get 'upload'
      get 'search'
      get 'add'
      get 'friends'
    end

  end

  resources :song do
    collection do
      get 'search'
      get 'play'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :songs
  # attr_accessible :title, :body
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :idfriend

  belongs_to :user

  #validates_uniqueness_of :idfriend

end

app/models/historic.rb
class Historic < ActiveRecord::Base
  belongs_to :user
  # attr_accessible :title, :body
end

app/models/pianizm.rb
class Pianizm < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :users
  has_many :songs

  def self.autenticarUsuario(login, password)
    user = User.find_by_login(login)
    return false if user.nil?
    return user.autenticar(password)
  end


end

app/models/song.rb
class Song < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :pianizm
  belongs_to :user
  belongs_to :category
  belongs_to :song_list
  attr_accessible :name,:length,:score,:author
end

app/models/song_list.rb
class SongList < ActiveRecord::Base
  has_many :songs
  belongs_to :user

  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :login, :password, :rol, :name
  belongs_to :pianizm
  has_many :friends
  has_many :songs
  has_many :song_lists
  has_one :historic

  # Constraints
  # No nil ni 'corto'
  validates_presence_of :login , :message => 'El login no puede ser vacio'
  validates_length_of :login, :minimum => 1 ,:message => 'Login muy corto'
  validates_presence_of :password ,:message => 'La clave no puede ser vacia'
  validates_length_of :password, :minimum => 8  ,:message => 'La clave debe tener 8 caracteres'
  validates_presence_of :rol
  validates_presence_of :name ,:message => 'El nombre no puede ser vacio'
  validates_length_of :name, :minimum => 3 ,:message => 'El nombre debe tener 3 o mas caracteres'

  # Uniqueness
  validates_uniqueness_of :login , :message => 'Ese login ya se encuentra en uso'

  #Methods
  def autenticar(password)
    return self.password.eql?(password)
  end

   #metodo que agrega un amigo al usuario en sesion
  def self.addFriend (idFriend)
      #Friend.new(user: self.id, idfriend: idFriend).save
      self.friends.new(idfriend: idFriend).save
  end

  # Metodo que busca los usuarios por el parámetro de búsqueda asociado.
  # Si es un login, retorna el usuario al que le pertenece. Si es un nombre, busca todos los asociados.
  def self.searchFriend(search)
    u= []
    us= User.find_by_login(search)
    if(us.nil?)
      if (!search.nil?)
        u= User.find_all_by_name(search)
        uu= User.find_all_by_name(search.capitalize)
        uuu= User.find_all_by_rol(search.capitalize)
        arr= search.strip.split(" ")
        string=''
        arr.each do |w|
          string+= w+' '
        end
        uuuu= User.find_all_by_name(string.strip)
        uuuuu= User.where("name like ?", "%#{search}%")
        uuuuuu= User.where("name like ?", "%#{search.capitalize}%")
        uuuuuuu= User.where("rol like ?", "%#{search.capitalize}%")
        uuuuuuuu= User.where("login like ?", "%#{search}%")

        c=u|uu|uuu|uuuu|uuuuu|uuuuuu|uuuuuuu|uuuuuuuu
        return c
      end
      return u
    else
      u.push(us)
      return u
    end

    #if !search.nil?
      #string ="select * from users where users.name like "+ search.to_s + " or users.name like " + search.to_s.capitalize + " or users.login like "+ search.to_s + " or users.rol like " + search.to_s.capitalize
     # string='select * from users where 1=2'
      #u2= User.find_by_sql(string)
    #else
     # u2=[]
    #end
    #c= u|u2


  end

  #retorna todas las canciones subidas por un tutor
  def self.getUploadedSongs(login)
    songs=Song.find_all_by_author(login)
    return songs
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_user
    @_current_user ||= session[:current_user_id] &&
        (User.find_by_id(session[:current_user_id]))
  end
end

app/controllers/pianizm_controller.rb
# encoding: utf-8
class PianizmController < ApplicationController


  def index
   # User.new(login: 'Diego', password: 'soydiego', rol: 'Tutor').save


  end

  def  create
    login = params[:username]
    password = params[:password]
    res = Pianizm.autenticarUsuario(login, password)
    if res
      id= User.find_by_login(login).id
      session[:current_user_id] = id
      redirect_to user_index_path
     # redirect_to edit_user_path(id)
    else
      flash[:title]='Error'
      flash[:notice]='Usted no existe en el sistema, por favor regístrese'
      redirect_to pianizm_index_path
    end
  end
  def new

  end
  def edit

  end

  def show

  end

  def destroy
    # Remove the user id from the session
    @_current_user = session[:current_user_id] = nil
  end

  def logout
    destroy
    flash[:title] = 'Información'
    flash[:notice] = 'Ha cerrado sesión correctamente'
    redirect_to pianizm_index_path
  end
end

app/controllers/song_controller.rb
class SongController < ApplicationController

  def index

  end

  def new

  end

  def edit

  end

  def create

  end

  def search
    @search= params[:search].downcase
  end

  def play

  end
end

app/controllers/user_controller.rb
# encoding: utf-8
class UserController < ApplicationController

  def index
    id = session[:current_user_id]
    @login= User.find(id).login
    @userName= User.find(id).name

  end


  def create
    login = params[:username].downcase
    password = params[:password]
    rol = params[:rol]
    @nombreSplit= params[:name].split(" ")
    nombre= ""
    if @nombreSplit.length >0
      @nombreSplit.each do |n|
      nombre= nombre+ n.capitalize+" "
      end
    else
       nombre=@nombreSplit.capitalize.strip
    end


    User.new(login: login, password: password, rol: rol, name: nombre.strip).save

    if(login.empty? or password.empty? or nombre.empty?)
      flash[:title]='¡Error!'
      flash[:notice]='Los datos son incorrectos, por favor verifiquelos'
    else
      flash[:title]='¡Exito!'
      flash[:notice]='Su cuenta ha sido creada exitosamente. Por favor haga login'
    end


    redirect_to pianizm_index_path

  end

  def upload

  end

  def search
    @search= params[:search]
    @result= User.searchFriend(@search)
    return @result
  end

  def add

  end

  def show
    @userId=params[:id]
    @usr= User.find(@userId)
    @usrUploadedSongs= User.getUploadedSongs(@usr.login)
    @booleanFriends= false
    @currentUser= User.find(session[:current_user_id])

    @usrId= params[:usrId]
    @boolean= params[:booleanAdd]
    if( !@usrId.nil? or !@boolean.nil? )
      puts 'testeo'
      puts @usrId
      u= User.find(session[:current_user_id])
      u.friends.new(idfriend: @usrId).save
      puts 'tam friends'
      puts u.friends.size
        puts 'WIN'
      flash[:title]='¡Información!'
      flash[:notice]='Amigo agregado exitosamente'
    else
      #flash[:title]='¡ERROR!'
      #flash[:notice]='Tu amigo no fue agregado'
    end



  end

  def friends
  @friends= Friend.find_all_by_user_id(session[:current_user_id])
    puts 'hey'
    puts @friends.size
    puts @friends
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/pianizm_helper.rb
module PianizmHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_css.html.erb
<!-- CSS -->
<%= stylesheet_link_tag 'application' %>

<!-- Header Script -->
<%= javascript_include_tag 'application' %>

app/views/layouts/_javascript.html.erb
<!-- JavaScript -->
<%= javascript_include_tag 'bootstrap.min.js' %>


<script type="text/javascript">
     <% if flash[:notice] %>
        $('#modal').modal('show');
    <% end %>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
     <title>Pianizm.com</title>
     <%= render 'layouts/css' %>
     <%= csrf_meta_tags %>
    </head>
    <body>
        <%= yield %>
    </body>
<%= render 'layouts/javascript' %>
</html>

app/views/pianizm/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href= 'pianizm'> Pianizm.com </a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <% if current_page?(pianizm_index_path)%>
              <li class="active"><%= link_to 'Home', pianizm_index_path %></li>
              <li><%= link_to 'About', pianizm_index_path %></li>
              <li><%= link_to 'Contact', pianizm_index_path %></li>
          <% end %>
          </li>
        </ul>
        <% puts 'searchme' %>
        <% puts session[:current_user_id].nil?.to_s %>
        <% puts  session[:current_user_id] %>

        <% if session[:current_user_id].nil?%>
        <%= form_tag pianizm_index_path, :class => 'navbar-form pull-right', :method => :post %>
        <input id="usernamelog"class="span2" type="text" placeholder="Email" name="username">
        <input id="passwordlog" class="span2" type="password" placeholder="Password" name="password">
        <button id="signinlog" type="submit" class="btn">Sign in</button>
        </form>
        <% else %>
            <p class="navbar-text pull-right">
              Logged in as  <%= link_to User.find(session[:current_user_id]).login, user_index_path %>
            </p>
        <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/pianizm/index.html.erb
<%= render 'pianizm/navbar'%>
<div class="container-fluid">
  <div class="row-fluid">
      <div class="span8">
        <div class="hero-unit">
          <h1>  <%= image_tag 'logo.png', :size => '150x20', :class => 'brand'%> Te da la bienvenida</h1>
          <p class="lead"> Pianizm es una comunidad web que surge de la necesidad de aprender y enseñar a tocar piano.
            En esta comunidad puedes participar como tutor y/o aprendiz, por lo que puedes grabar o tocar canciones. Te
            invitamos a registrarte para probar una nueva experiencia de aprendizaje musical.
          </p>  <p><a href="#" class="btn btn-primary btn-large">Conoce más &raquo;</a></p>
        </div>
      </div>
      <div class="span4">
        <h2>Registrate ahora</h2>
        <%= form_tag  user_index_path, method: 'post' %>
        <span class="help-block">Por favor ingresa tu nombre, login y clave.</span>
        <input type="text" placeholder="Nombre" name="name">
        <input type="text" placeholder="Email" name="username">
        <input type="password" placeholder="Password" name="password"> <br>
        <span class="help-block">Por favor selecciona un rol.</span>
        <select name="rol">
          <option>Aprendiz</option>
          <option>Tutor</option>
          <option>Ambos</option>
        </select><br>
        <button type="submit" class="btn">Registrar</button>
        </form>
      </div>
  </div>
</div>

<%= render 'shared/footer' %>
<%= render 'shared/modalFlash' %>

app/views/shared/_footer.erb
<div id="footer">
  <div class="container">
    <p class="muted credit">EN ESTE FOOTER IRÁ LA PUBLICIDAD</p>
  </div>
</div>

app/views/shared/_matrix4.erb
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">

      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Canciones tocadas</li>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Canción 1</a></li>
          <li><a href="#">Canción 2</a></li>
          <li><a href="#">Canción 3</a></li>
          <li><a href="#">Canción 4</a></li>
          <li><a href="#">Canción 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>

      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Generos Favoritos</li>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Género 1</a></li>
          <li><a href="#">Género 2</a></li>
          <li><a href="#">Género 3</a></li>
          <li><a href="#">Género 4</a></li>
          <li><a href="#">Género 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>

    </div>
    <div class="row-fluid">
      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Canciones subidas</li>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Canción 1</a></li>
          <li><a href="#">Canción 2</a></li>
          <li><a href="#">Canción 3</a></li>
          <li><a href="#">Canción 4</a></li>
          <li><a href="#">Canción 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>

      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Amigos Seguidos</li>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Amigo 1</a></li>
          <li><a href="#">Amigo 2</a></li>
          <li><a href="#">Amigo 3</a></li>
          <li><a href="#">Amigo 4</a></li>
          <li><a href="#">Amigo 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modalFlash.html.erb
<% if flash[:notice] %>
    <div class="modal hide fade" id="modal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><%= flash[:title]  %></h3>
      </div>
      <div class="modal-body">
        <%= flash[:notice]  %>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
<% end %>

app/views/song/_matrix4song.erb
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">

      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Contienen <%= @search %></li>
          <li class="active"><a href="#">Home</a></li>
          <li><%= link_to 'Canción 1', play_song_index_path %></li>
          <li><a href="#">Canción 2</a></li>
          <li><a href="#">Canción 3</a></li>
          <li><a href="#">Canción 4</a></li>
          <li><a href="#">Canción 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>

      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Mejor Puntuadas</li>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Género 1</a></li>
          <li><a href="#">Género 2</a></li>
          <li><a href="#">Género 3</a></li>
          <li><a href="#">Género 4</a></li>
          <li><a href="#">Género 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>

    </div>
    <div class="row-fluid">
      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Tocadas por amigos</li>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Canción 1</a></li>
          <li><a href="#">Canción 2</a></li>
          <li><a href="#">Canción 3</a></li>
          <li><a href="#">Canción 4</a></li>
          <li><a href="#">Canción 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>

      <div class="span6">
        <ul class="nav nav-list">
          <li class="nav-header">Subidas por amigos</li>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Amigo 1</a></li>
          <li><a href="#">Amigo 2</a></li>
          <li><a href="#">Amigo 3</a></li>
          <li><a href="#">Amigo 4</a></li>
          <li><a href="#">Amigo 5</a></li>
          <li><a href="#">Más...</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/song/_navbarsong.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="pianizm">Pianizm.com</a>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          Logged in as  <%= link_to User.find(session[:current_user_id]).login, user_index_path %>
        </p>

        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          <li><%= link_to 'Sign Out', logout_pianizm_index_path,:confirm => "Are you sure?", :method => :get %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/song/_playhub.erb
<div class="row-fluid">
  <div class="span12">
    ACA IRÁ EL NOMBRE DE LA CANCIÓN
    <div class="row-fluid">
      <div class="span8">
        <div class="row-fluid" >
         ACÁ IRÁ EL COMPONENTE PARA GRABAR Y TOCAR CANCIONES
        <%= image_tag 'pianizmplayhub.png', :size => '705x362', :class => 'brand'%>
        </div>
      </div>
      <div class="span4">
        <div class="span12">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Opciones cancion actual</li>
              <li><%= link_to 'Revisar Progreso ', pianizm_index_path %></li>
              <li><%= link_to 'Guardar notas ', pianizm_index_path %></li>
              <li><%= link_to 'Comentar ', pianizm_index_path %></li>
              <li><%= link_to 'Ver autor', pianizm_index_path %></li>
              <li><%= link_to 'Taggear', pianizm_index_path %></li>
              <li class="nav-header">Canciones Similares</li>
              <li><%= link_to 'Canción 1 ', pianizm_index_path %></li>
              <li><%= link_to 'Canción 2 ', pianizm_index_path %></li>
              <li><%= link_to 'Canción 3 ', pianizm_index_path %></li>
              <li><%= link_to 'Canción 4', pianizm_index_path %></li>
              <li><%= link_to 'Canción 4', pianizm_index_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div>
    </div>
  </div>
</div>

app/views/song/_sidebar.html.erb
      <div class="span12">
        <div class="well sidebar-nav">
          <ul class="nav nav-list">
            <li class="nav-header">Canciones</li>
            <li><%= link_to 'Más buscadas ', pianizm_index_path %></li>
            <li><%= link_to 'Mejor puntuadas ', pianizm_index_path %></li>
            <li><%= link_to 'Más largas ', pianizm_index_path %></li>
            <li><%= link_to 'Por dificultad ', pianizm_index_path %></li>
            <li><%= link_to 'Por Género', pianizm_index_path %></li>
          </ul>
        </div><!--/.well -->
      </div><!--/span-->

app/views/song/index.html.erb
<%= render 'song/navbarsong' %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <%= render 'song/sidebar' %>
    </div>
    <div class="span10">
      <!--Body content-->
      <span class="helper-block">Por favor ingresa tu cosulta</span>
      <%= form_tag search_song_index_path, :class => 'form-search',:id=>'searchform', :method => :get %>
      <input type="text" class="input-medium search-query" name="search" required="">
      <button type="submit" class="btn"><i class="icon-search"></i>Search</button>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/song/play.erb
<%= render 'song/navbarsong' %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <%= render 'song/sidebar' %>
    </div>
    <div class="span10">
      <!--Body content-->
      <%= render 'song/playhub' %>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/song/search.erb
<%= render 'song/navbarsong' %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <%= render 'song/sidebar' %>
    </div>
    <div class="span10">
      <h2>Estas son las canciones encontradas al buscar <%= @search %></h2>
      <%= render 'song/matrix4song' %>
    </div>
  </div>
</div>

</form>

<%= render 'shared/footer' %>

app/views/user/_friendTable.erb
<% if @friends.size.eql?(0) %>

    <h3>Aún no tienes amigos. Te invitamos a buscar amigos <%= link_to 'acá' , search_user_index_path%></h3>
<% else %>
    <table class="table table-striped">
      <tr>
        <th>Login</th>
        <th>Nombre</th>
        <th>Rol</th>
        <th>Ver Perfil</th>
      </tr>
      <% @friends.each do |friend| %>
          <% usuario= User.find(friend.idfriend)  %>
          <% if session[:current_user_id].eql?(usuario.id)  %>

          <% else %>
              <tr>
                <td><%= usuario.login %></td>
                <td><%= usuario.name %></td>
                <td><%= usuario.rol %></td>
                <td><%= link_to 'Perfil',user_path(usuario.id)  %></td>
              </tr>
          <% end %>
      <% end %>
    </table>
<% end %>

app/views/user/_navbaruser.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="pianizm">Pianizm.com</a>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          Logged in as  <%= link_to User.find(session[:current_user_id]).login, user_index_path %>
        </p>

        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          <li><%= link_to 'Sign Out', logout_pianizm_index_path,:confirm => "Are you sure?", :method => :get %></li>

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/user/_results.erb
<% if @result.size.eql?(0) %>
  <h2>No hay resultados por <%= @search %></h2>
<% else %>
<table class="table table-striped">
  <tr>
    <th>Login</th>
    <th>Nombre</th>
    <th>Rol</th>
    <th>Ver Perfil</th>
  </tr>
  <% @result.each do |usuario| %>
  <% if session[:current_user_id].eql?(usuario.id)  %>

  <% else %>
  <tr>
    <td><%= usuario.login %></td>
    <td><%= usuario.name %></td>
    <td><%= usuario.rol %></td>
    <td><%= link_to 'Perfil',user_path(usuario.id)  %></td>
  </tr>
  <% end %>
 <% end %>
</table>
<% end %>

app/views/user/_sidebar.html.erb
      <div class="span12">
        <div class="well sidebar-nav">
          <ul class="nav nav-list">
            <li class="nav-header">Amigos</li>
            <li><%= link_to 'Buscar Amigos ', search_user_index_path %></li>
            <li><%= link_to 'Ver Amigos ', friends_user_index_path %></li>
            <li class="nav-header">Mis Canciones</li>
            <li><%= link_to 'Buscar Canciones', song_index_path %></li>
            <li><%= link_to 'Mis canciones', pianizm_index_path %></li>
            <% if User.find(session[:current_user_id]).rol.eql?('Tutor') or  User.find(session[:current_user_id]).rol.eql?('Ambos') %>
            <li class="nav-header">Zona Tutor</li>
            <li><%= link_to 'Subir Cancion', upload_user_index_path %></li>
            <li><%= link_to 'Mis estudiantes', pianizm_index_path %></li>
            <% end %>
          </ul>
        </div><!--/.well -->
      </div><!--/span-->

app/views/user/_viewProfile.erb
<h2>Estás viendo el perfil de <%= @usr.name %>
 <% string= "select * from friends where friends.idfriend=" + @usr.id.to_s+ " and user_id=" + @currentUser.id.to_s  %>
 <% @esAmigo= !@currentUser.friends.find_by_sql(string).first.nil? %>
 <% if @esAmigo %>
      <div style="float: left; width: auto;"> <%= button_to 'Unfriend', pianizm_index_path, :class => 'btn btn-danger' , :method => :get  %> </div>
 <% else %>
      <div style="float: left; width: auto;"><%= form_tag  user_path(@usr.id), :method=> :get %>
      <input type="hidden"  value="add" name="booleanAdd"></input>
      <input type="hidden"  value="<%= @usr.id %>" name="usrId"></input>
      <button type="submit" class="btn btn-info" style="display: inline"><i class="icon-user"></i>Add Friend</button>
      </div>
 <% end %>
</h2>
<%= render 'shared/matrix4' %>
<%= render 'shared/modalFlash' %>

app/views/user/add.html.erb
Hello World <%= @userId %>

app/views/user/friends.html.erb
<%= render 'user/navbaruser'%>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <%= render 'user/sidebar' %>
    </div>
    <div class="span10">
      <!--Body content-->
      <h2>Estos son tus amigos:</h2>
      <%= render 'user/friendTable' %>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/user/index.html.erb
<%= render 'user/navbaruser' %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <%= render 'user/sidebar' %>
    </div>
    <div class="span10">
      <!--Body content-->
      <h1>Hola <%= @userName %></h1>
      <%= render 'shared/matrix4' %>
    </div>
  </div>
</div>

</form>
<%= render 'shared/footer' %>

app/views/user/search.erb
<%= render 'user/navbaruser' %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <%= render 'user/sidebar' %>
    </div>
    <div class="span10">
      <!--Body content-->
      <span class="helper-block">Por favor ingresa tu cosulta</span>
      <%= form_tag search_user_index_path, :class => 'form-search', :id=>'searchform', :method => :get %>
      <input type="text" class="input-medium search-query" name="search" id="searchinput" required="true">
      <button type="submit" class="btn" id="searchbtn"><i class="icon-search"></i>Search</button>
      <% if @search.nil? == true %>
         <h2>Acá aparecerán los resultados de tu búsqueda de amigos</h2>
      <% else %>
      <%= render 'user/results' %>
      <% end %>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/user/show.html.erb
<%= render 'user/navbaruser' %>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <%= render 'user/sidebar' %>
    </div>
    <div class="span10">
      <!--Body content-->
      <%= render 'user/viewProfile' %>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/user/upload.html.erb
HELLO WORLD
<%= render 'shared/footer' %>